alias ll='ls -l'
alias la='ls -A'
alias ..='cd ..'
alias gs='git status'
alias glo='git log --oneline'
alias dotfiles='/usr/bin/git --git-dir=/home/yorly/.dotfiles/ --work-tree=/home/yorly'
alias ds='dotfiles status'
#alias l='ls -CF'
