# GENERAL APPEARANCE 
# Background(bg) ; Foreground(fg)
bg        = 0x001F1F28
fg        = 0x00DDD8BB
error_bg  = 0x001F1F28
error_fg  = 0x01FF0000
border_fg = 0x00DDD8BB

# Input box active by default on startup
default_input = password

# The character used to mask the password
asterisk = *

# Erase password input on failure
clear_password = true

allow_empty_password = false

# Remove version number 
hide_version_string = true

# Identifier for battery whose charge to display at top left
battery_id = BAT0

# Format string for clock in top right corner (Wed 15 Jul 20:31)
clock = %a %d %b %H:%M

# KEY COMBINATIONS 
sleep_key           = F3
restart_key         = F2
shutdown_key        = F1
hibernate_key       = F4
show_password_key   = F7
brightness_up_key   = F6
brightness_down_key = F5
