# GENERAL APPEARANCE 
# Input box active by default on startup
default_input = password

# The character used to mask the password
asterisk = *

# Erase password input on failure
clear_password = true

allow_empty_password = false

# Remove version number 
hide_version_string = true

# Remove keyboard lock states from the top right corner
hide_keyboard_locks = true

# Hide session in xinitrc
xinitrc = null

# Identifier for battery whose charge to display at top left
battery_id = BAT0

# Format string for clock in top right corner (Wed 15 Jul 20:31)
clock = %a %d %b %H:%M

# KEY COMBINATIONS AND COMMANDS
show_password_key   = F9
sleep_key           = F10
restart_key         = F11
shutdown_key        = F12

# Command executed when starting Ly (before the TTY is taken control of)
start_cmd = /usr/local/bin/kanagawa-tty

# Command executed when pressing sleep key (can be null)
sleep_cmd = systemctl suspend
